# Generated by Django 5.2.7 on 2025-11-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='cuisines',
        ),
    ]
